### PR TITLE
fixes #390. Removal of exposedPorts parameter

### LINKED ISSUE #390: Remove exposedHostPorts option
Due to new insights, we now want to get rid of published ports on Docker machine installs.

First, the name is incorrect because we're not just exposing ports, we're publishing them on the host.

Second, without published ports we can run multiple instances of the same service and expose the default port.

This will lead up to Weave net load balancing over the instances. And later to multiple host installs using Weave net.

### PR DESCRIPTION
**Pull request by sadovnikov**

### CODE REVIEW

File: minimesos/src/main/java/com/containersol/minimesos/mesos/MesosMasterContainer.java [hunk 1]
```diff
@@ -74,9 +74,6 @@ protected CreateContainerCmd dockerCommand() {
         ExposedPort exposedPort = ExposedPort.tcp(port);
```
Comment (containersol) [inline minimesos/src/main/java/com/containersol/minimesos/mesos/MesosMasterContainer.java]: MAJOR Remove this unused "exposedPort" local variable. [rule](https://ci.infra.container-solutions.com/sonar/coding_rules#rule_key=squid%3AS1481)
MAJOR Remove this useless assignment to local variable "exposedPort". [rule](https://ci.infra.container-solutions.com/sonar/coding_rules#rule_key=squid%3AS1854)

**Comment by containersol** [comment]
SonarQube analysis reported 2 issues:
* MAJOR 2 major

Watch the comments in this conversation to review them.

**Comment by frankscholten** [comment]
LGTM
